### ISSUE TITLE
Passport Image

### ISSUE THREAD

**Issue by ZAidBinAsif** [AppliedRecognition/Passport-Reader-Android-Sample#1]
How can i get the passport image after scan, and person image in passport. ?

**Comment by jakubdolejs** [comment]
- Extract the result from the intent passed to `onActivityResult`:
    ```java
    MRTDScanResult scanResult = data.getParcelableExtra(MRTDScanActivity.EXTRA_MRTD_SCAN_RESULT);
    ```
- Decode a bitmap from the image file:
    ```java
    Bitmap bitmap = BitmapFactory.decodeFile(scanResult.getImageFilePath());
    ```

The project's [README](https://github.com/AppliedRecognition/Passport-Reader-Android-Sample) has more examples.
